# Generated by Django 4.2 on 2026-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramesh', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
