# Generated by Django 4.2 on 2026-02-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramesh', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
