# Generated by Django 4.2 on 2026-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramesh', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_days',
            field=models.CharField(default='3-7 days', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Processing', max_length=20),
        ),
    ]
